// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp-LrhhkPow_z_Or48C20SwX0SkgY-HQs',
    appId: '1:608017073256:web:d349487b1236f5ea7667dd',
    messagingSenderId: '608017073256',
    projectId: 'fitflexclub-fa604',
    authDomain: 'fitflexclub-fa604.firebaseapp.com',
    storageBucket: 'fitflexclub-fa604.firebasestorage.app',
    measurementId: 'G-EFCKQB7RS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDePQDVTVJI0rnKeqo4od-y7CH4UUc7iYs',
    appId: '1:608017073256:android:f1bf49be9dd066797667dd',
    messagingSenderId: '608017073256',
    projectId: 'fitflexclub-fa604',
    storageBucket: 'fitflexclub-fa604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY2Dg9lRCUnhzxjJeEQDzog-4_4vx3ZIc',
    appId: '1:608017073256:ios:5280165f04b9696d7667dd',
    messagingSenderId: '608017073256',
    projectId: 'fitflexclub-fa604',
    storageBucket: 'fitflexclub-fa604.firebasestorage.app',
    iosBundleId: 'com.fitblitz.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY2Dg9lRCUnhzxjJeEQDzog-4_4vx3ZIc',
    appId: '1:608017073256:ios:5280165f04b9696d7667dd',
    messagingSenderId: '608017073256',
    projectId: 'fitflexclub-fa604',
    storageBucket: 'fitflexclub-fa604.firebasestorage.app',
    iosBundleId: 'com.fitblitz.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp-LrhhkPow_z_Or48C20SwX0SkgY-HQs',
    appId: '1:608017073256:web:2a5025857f99bd2d7667dd',
    messagingSenderId: '608017073256',
    projectId: 'fitflexclub-fa604',
    authDomain: 'fitflexclub-fa604.firebaseapp.com',
    storageBucket: 'fitflexclub-fa604.firebasestorage.app',
    measurementId: 'G-ZDF4HBW2R9',
  );

}